1.18 forge
teaconmc/SlideShow pull request #11
Opened 2022-01-18 15:47 UTC by BloCamLimb

Not working: Projector Highlight, Permission Resolver

2022-01-19 10:06 UTC, ustc-zzzz requested changes

2022-01-19 10:06 UTC, ustc-zzzz commented on src/main/java/org/teacon/slides/projector/ProjectorBlock.java
> +        InternalRotation(@Nullable Quaternion rotation) {
不要用四元数，四元数的 sqrt(2) 会导致浮点数的舍入误差。旋转矩阵的每一项都是整数。

2022-01-19 10:06 UTC, ustc-zzzz commented on src/main/java/org/teacon/slides/projector/ProjectorBlock.java
> +        InternalRotation(@Nullable Quaternion rotation) {
Fine，可能也不会（小声 bb）。

2022-01-19 10:06 UTC, ustc-zzzz commented on src/main/java/org/teacon/slides/projector/ProjectorContainerMenu.java
> +            CompoundTag tag = buf.readNbt();
换成 `Objects.requireNonNull`（超小声 bb）。

2022-01-19 10:06 UTC, ustc-zzzz commented on src/main/java/org/teacon/slides/renderer/Slide.java
> +public abstract class Slide implements AutoCloseable {
海豹化（bushi）这个类（加上 `sealed`）。

2022-01-19 10:06 UTC, ustc-zzzz commented on src/main/java/org/teacon/slides/renderer/Slide.java
> +             * fmt = '    builder.pos(matrix, {}, {}, {}).color(255, 255, 255, alpha).tex({}, {}).lightmap(light)
把 generation code 同步改了（超小声 bb）。

2022-01-19 10:06 UTC, ustc-zzzz commented on src/main/java/org/teacon/slides/renderer/SlideState.java
> +    private static volatile HashMap<String, SlideState> sCache = new HashMap<>();
这里应该没有非 render thread 的操作吧（超超超小声 bb）。

2022-01-19 15:37 UTC, ustc-zzzz approved these changes

2022-01-20 09:31 UTC, jihuayu approved these changes
改得好！

2022-01-20 19:50 UTC, merged